name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  collection:
    uses: n4o-rse/n4o-kg-profile/.github/workflows/collection.yml@v1
    with:
      strict: true
